# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-signaling-modules"
publish = false
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
opentalk-signaling-core.workspace = true

opentalk-signaling-module-asset-storage.workspace = true
opentalk-signaling-module-automod.workspace = true
opentalk-signaling-module-breakout.workspace = true
opentalk-signaling-module-chat.workspace = true
opentalk-signaling-module-core.workspace = true
opentalk-signaling-module-echo.workspace = true
opentalk-signaling-module-legal-vote.workspace = true
opentalk-signaling-module-livekit.workspace = true
opentalk-signaling-module-meeting-notes.workspace = true
opentalk-signaling-module-meeting-report.workspace = true
opentalk-signaling-module-moderation.workspace = true
opentalk-signaling-module-polls.workspace = true
opentalk-signaling-module-recording.workspace = true
opentalk-signaling-module-shared-folder.workspace = true
opentalk-signaling-module-subroom-audio.workspace = true
opentalk-signaling-module-timer.workspace = true
opentalk-signaling-module-training-participation-report.workspace = true
opentalk-signaling-module-whiteboard.workspace = true

async-trait.workspace = true
