// SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
//
// SPDX-License-Identifier: EUPL-1.2

mod event_training_participation_report_inventory;
mod event_training_participation_report_parameter_set;
mod update_event_training_participation_report_parameter_set;

pub use event_training_participation_report_inventory::EventTrainingParticipationReportInventory;
pub use event_training_participation_report_parameter_set::EventTrainingParticipationReportParameterSet;
pub use update_event_training_participation_report_parameter_set::UpdateEventTrainingParticipationReportParameterSet;
