# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-r3dlock"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
redis = { workspace = true, features = ["tokio-comp"] }
tokio = { workspace = true, features = ["time"] }

rand.workspace = true
snafu.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
serial_test.workspace = true
tokio = { workspace = true, features = ["macros", "test-util"] }
