# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2
---
spec:
  inputs:
    release_version:
      description: |
        Version number, e.g. `1.2.3`. Must be in format `<major>.<minor>.<patch>`.
        Keep at `0.0.0` unless you're in the process of creating a release.
      type: string
      regex: ^([0]|([1-9]\d*))\.([0]|([1-9]\d*))\.([0]|([1-9]\d*))$
      default: 0.0.0
    release_issue:
      description: |
        The number of an issue which should be closed by a release MR created by this pipeline.
        Keep empty or unset unless you're in the process of creating a release.
      type: string
      regex: ^\d*$
      default: ''
---
image:
  name: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.94-trixie
  pull_policy: if-not-present

stages:
  - lint
  - test
  - build
  - check
  - package
  - trigger
  - release

variables:
  OPENTALK_CONTROLLER_PROJECT: opentalk-controller
  # Enable one network per build for the test container and services
  FF_NETWORK_PER_BUILD: 'true'
  # Will be set to the same namespace as the source project for a MR,
  # or the same namespace as the current project for the `main` branch.
  # Can be overridden entirely from project settings.
  KANIKO_IMAGE: git.opentalk.dev:5050/opentalk/opentalk-devops/containers/kaniko:debug-1.25
  SKOPEO_IMAGE: quay.io/skopeo/stable:v1.20
  DEFAULT_FLAVOR: trixie

.template_vars:
  FLAVORS: [trixie, noble, scratch]

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'

include:
  - project: opentalk/ci/templates/collect-commit-evidence
    ref: v2
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/release-creation
    inputs:
      version: $[[ inputs.release_version ]]
      issue: $[[ inputs.release_issue]]
    ref: v1
    file: .gitlab-ci-template.yml

trigger_changelog_preview:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    PIPELINE_PROJECT_PATH: $CI_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_PROJECT_PATH: $CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
    PIPELINE_MERGE_REQUEST_SOURCE_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    PIPELINE_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
  trigger: opentalk/tools/check-changelog

lint:fmt:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  <<: *default_job_condition
  script:
    - cargo clippy --workspace --all-features --tests -- --deny warnings

lint:doc:
  stage: lint
  <<: *default_job_condition
  variables:
    RUSTDOCFLAGS: -Dwarnings
  script: cargo doc --workspace --no-deps

lint:shellcheck:
  image:
    name: koalaman/shellcheck-alpine:v0.11.0
    pull_policy: if-not-present
  stage: lint
  <<: *default_job_condition
  before_script:
    - apk update
    - apk add git
  script: git ls-files "*.sh" -z | xargs -0r shellcheck

lint:dependency_check:
  stage: lint
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - Cargo.lock
        - deny.toml
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - >
      cargo-deny --all-features --workspace check
      --deny unmatched-skip
      --deny license-not-encountered
      --deny advisory-not-detected
      --hide-inclusion-graph

lint:unnecessary_dependencies:
  stage: lint
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script: if ! cargo machete --version; then cargo install cargo-machete; fi
  script: cargo machete --with-metadata

lint:yaml:
  stage: lint
  <<: *default_job_condition
  image:
    name: alpine:3.23
    pull_policy: if-not-present
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:toml:
  stage: lint
  <<: *default_job_condition
  script: taplo fmt --check

lint:openapi:
  stage: lint
  <<: *default_job_condition
  image:
    name: redocly/cli:1.34.11
    entrypoint: ['']
    pull_policy: if-not-present
  script:
    - /usr/local/bin/openapi lint docs/developer/api.yaml

lint:openapi-spectral:
  stage: lint
  <<: *default_job_condition
  image:
    name: stoplight/spectral:6.15
    entrypoint: ['']
    pull_policy: if-not-present
  script:
    - spectral lint --ruleset ci/spectral/openapi.yml lint docs/developer/api.yaml

lint:markdown:
  stage: lint
  <<: *default_job_condition
  image:
    name: registry.gitlab.com/pipeline-components/markdownlint:0.14.5
    pull_policy: if-not-present
  script:
    - mdl --warnings .

lint:licensing:
  stage: lint
  <<: *default_job_condition
  image:
    name: fsfe/reuse:6.2
    entrypoint: ['']
    pull_policy: if-not-present
  script:
    - reuse lint

lint:commit:
  cache: {}
  image:
    name: node:lts-alpine
    pull_policy: if-not-present
  stage: lint
  needs: []
  rules:
    # Run in merge requests only.
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:justfile:
  stage: lint
  <<: *default_job_condition
  before_script: if ! just --version; then cargo install just; fi
  script:
    # The `--fmt` command-line parameter is still unstable, but valuable anyway.
    - just --unstable --fmt --check

test:load_typst_plugins:
  stage: test
  <<: *default_job_condition
  needs: []
  artifacts:
    paths:
      - target/typst
    expire_in: 1 day
  image:
    name: git.opentalk.dev:5050/opentalk/backend/containers/typst-plugins:alpine-dev
    pull_policy: if-not-present
  script:
    - mkdir -p target
    - cp -r /usr/share/typst target/typst

test:cargo_test:
  stage: test
  <<: *default_job_condition
  needs:
    - test:load_typst_plugins
  artifacts:
    reports:
      junit: target/nextest/ci/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: target/llvm-cov-target/cobertura.xml
  # this uses region for coverage summary
  coverage: /TOTAL\s+(\d+\s+)+(\d+\.\d+\%)/
  variables:
    # Set ENV vars for services
    POSTGRES_DB: opentalk
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    # Used for integration tests
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    DATABASE_NAME: opentalk
    KUSTOS_TESTS_DATABASE_URL: postgres://postgres:password123@postgres:5432/kustos
    REDIS_ADDR: redis://redis:6379/
    TYPST_PACKAGE_CACHE_PATH: $CI_PROJECT_DIR/target/typst/packages
  services:
    - name: postgres:18-alpine
      alias: postgres
    - name: redis:8-alpine
      alias: redis
  script:
    - pwd
    - ls
    - RUSTFLAGS="-C link-arg=-fuse-ld=lld"
    - cargo llvm-cov --no-report nextest --profile ci --workspace --locked
    # code coverage for doctests is unstable, so we run them separately
    - cargo test --doc --workspace --locked
    - cargo llvm-cov report --cobertura --output-path target/llvm-cov-target/cobertura.xml
    - cargo llvm-cov report --summary-only

test:cargo_xtask:
  stage: test
  <<: *default_job_condition
  variables:
    POSTGRES_DB: opentalk
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    DATABASE_NAME: opentalk
  services:
    - name: postgres:18-alpine
      alias: postgres
  script:
    - cargo install diesel_cli --version ~2 --no-default-features --features="postgres"
    # Verify that the HEAD schema.rs matches the actual HEAD migration database schema.
    - RUST_LOG=error cargo xtask verify-db-schema --postgres-url="${POSTGRES_BASE_URL}"

build:
  stage: build
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Tags must be in the form of vMAJOR.MINOR.PATCH
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    VERGEN_GIT_SHA: $CI_COMMIT_SHA
    VERGEN_GIT_BRANCH: $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - target/release/opentalk-controller
    expire_in: 1 week
  before_script:
    - apt-get --update install -y libpq-dev musl-tools protobuf-compiler
  script:
    - cargo auditable build --release --locked --workspace

check:er-diagram:
  stage: check
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - target/docs/temporary/database/er-diagram.mermaid
  variables:
    # Set ENV vars for services
    POSTGRES_DB: opentalk
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password123
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_BASE_URL: postgres://postgres:password123@postgres:5432
    OPENTALK_CTRL_DATABASE__URL: postgres://postgres:password123@postgres:5432/opentalk
  services:
    - name: postgres:18-alpine
      alias: postgres
  script:
    - ci/docs-generate-mermaid.sh

check:docs-generated-parts:
  stage: check
  image:
    name: git.opentalk.dev:5050/opentalk/tools/opentalk-ci-doc-updater:v0.2.0
    entrypoint: ['']
    pull_policy: if-not-present
  needs:
    - job: build
      artifacts: true
    - job: check:er-diagram
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script:
    - apt-get --update install -y git
  script:
    - ci/docs-update-generated-parts.sh
    - |
      if ! git diff --exit-code; then
        echo "Generated parts of documentation changed, run ci/docs-update-generated-parts.sh and commit the result"
        exit 1
      fi

check:openapi:
  stage: check
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - ./ci/update-openapi-spec.sh
    - |
      if ! git diff --ignore-space-at-eol --exit-code --submodule=diff; then
        echo "Generated parts of documentation changed, run ci/update-openapi-spec.sh and commit the result"
        exit 1
      fi

build:docs:
  stage: build
  image:
    name: git.opentalk.dev:5050/opentalk/backend/containers/mkdocs-material:latest
    entrypoint: ['']
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - site/
  script:
    - mkdocs build --config-file "$CI_PROJECT_DIR"/mkdocs.yml --strict

build:pages:
  stage: build
  image:
    name: git.opentalk.dev:5050/opentalk/backend/containers/mkdocs-material:latest
    entrypoint: ['']
    pull_policy: if-not-present
  pages:
    publish: site
  needs: []
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script: []
  script:
    - mkdocs build --config-file "$CI_PROJECT_DIR"/mkdocs.yml --strict

package:read-tags:
  stage: package
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
  image:
    name: alpine/git:v2.52.0
    entrypoint: ['']
    pull_policy: if-not-present
  artifacts:
    reports:
      dotenv: package.env
  script:
    - git fetch --tags
    - TAGS=$(git tag --list | grep "^v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+$" | sort -V)
    - TAGS=$(echo "$TAGS" | sort -V | head -n -1 | tr "\n" " ")
    - echo "TAGS=$TAGS" > package.env

package:container-controller-mr:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  image:
    name: quay.io/buildah/stable:v1.43.0
    pull_policy: if-not-present
  artifacts:
    reports:
      dotenv: container.env
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "OPENTALK_CONTROLLER_IMAGE_NAME=$CI_REGISTRY_IMAGE" > container.env
    - echo "OPENTALK_CONTROLLER_IMAGE_TAG=$IMAGE_TAG" >> container.env
    - >
      IMAGE_TAG=$(
          echo -n "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" |
          tr -c '[:alnum:]_.-' '_' |
          sed 's/^[.-]/_/' |
          cut -c -63
      )
    - buildah build -f $CI_PROJECT_DIR/Dockerfile-$FLAVOR -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG-$FLAVOR"
    - buildah push "$CI_REGISTRY_IMAGE:$IMAGE_TAG-$FLAVOR"

trigger:service-integration-tests:
  stage: trigger
  variables:
    OPENTALK_CONTROLLER_IMAGE_TAG: dev
    OPENTALK_CONTROLLER_IMAGE_NAME: registry.heinlein.group/opentalk/controller
  needs:
    - job: package:container-controller-mr
      optional: true
    - job: push-and-sign-images-to-harbor
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  trigger:
    project: opentalk/qa/service-integration-tests
    branch: main
    forward:
      pipeline_variables: true

trigger-docs:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  trigger:
    project: opentalk/backend/docs

package:controller-container-build:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: quay.io/buildah/stable:v1.43.0
    pull_policy: if-not-present
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah build -f $CI_PROJECT_DIR/Dockerfile-$FLAVOR -t  "$CI_REGISTRY_IMAGE:$FLAVOR-${CI_COMMIT_SHA:0:8}"
    - buildah push "$CI_REGISTRY_IMAGE:$FLAVOR-${CI_COMMIT_SHA:0:8}"

package:controller-container-create-and-push-tags:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  needs:
    - job: package:read-tags
      optional: true
    - job: package:controller-container-build
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: $SKOPEO_IMAGE
    entrypoint: ['']
    pull_policy: if-not-present
  script:
    - TAGS_TO_PUSH=$(./ci/create-container-tags.sh "${CI_COMMIT_TAG:-main}" "$TAGS" "$FLAVOR" "$DEFAULT_FLAVOR")
    - |
      for tag in $TAGS_TO_PUSH; do
        skopeo copy \
        --src-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        --dest-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        "docker://${CI_REGISTRY_IMAGE}:$FLAVOR-${CI_COMMIT_SHA:0:8}" "docker://${CI_REGISTRY_IMAGE}:$tag"
      done
    - echo "TAGS_$FLAVOR=$TAGS_TO_PUSH" > package.env
  artifacts:
    reports:
      dotenv: package.env

push-and-sign-images-to-harbor:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  needs:
    - package:controller-container-create-and-push-tags
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: package
  variables:
    PIPELINE_FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE
    PIPELINE_NAMESPACE_SUFFIX: controller
    PIPELINE_TAGS_ENV_NAME: TAGS_$FLAVOR
  trigger:
    project: opentalk/opentalk-devops/push-and-sign-images-for-the-opentalk-namespace
    strategy: depend
    forward:
      pipeline_variables: true


read-trivy-ignore-file:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - echo "TRIVY_IGNORE_STR_$FLAVOR=$(
         cat $CI_PROJECT_DIR/.trivyignore-$FLAVOR | sed -n 'H;${x;s/^\n//;s/\n/\\n/g;p}'
      )"  > package.env
  artifacts:
    reports:
      dotenv: package.env

container-scanning:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  needs:
    - package:controller-container-build
    - read-trivy-ignore-file
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: package
  variables:
    PIPELINE_FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:dev-$FLAVOR
    PIPELINE_PROJECT_WITH_NAMESPACE: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    PIPELINE_ADDITIONAL_LABELS: team::conference management
    PIPELINE_TRIVY_IGNORE_FILE_STR_VAR: TRIVY_IGNORE_STR_${FLAVOR}
  trigger:
    project: opentalk/opentalk-devops/scan-container
    strategy: depend
    forward:
      pipeline_variables: true
