# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

ARG typst_plugins_version=dev
ARG typst_plugins_flavor=scratch

FROM git.opentalk.dev:5050/opentalk/backend/containers/static-libpostgres:v17.0 as static-libpostgres
FROM git.opentalk.dev:5050/opentalk/backend/containers/rust:1.94.0-alpine AS builder

RUN apk add --no-cache curl
RUN mkdir /controller

WORKDIR /controller

ADD . /controller

COPY --from=static-libpostgres /usr/lib/libpq.a /usr/lib/
COPY --from=static-libpostgres /usr/include/libpq /usr/include/

WORKDIR /controller

ENV LIBPQ_LIB_DIR=/usr/lib
ENV LIBPQ_INCLUDE_DIR=/usr/include
RUN cargo auditable build --release --locked --target=x86_64-unknown-linux-musl

RUN chmod +x /controller/target/x86_64-unknown-linux-musl/release/opentalk-controller

FROM git.opentalk.dev:5050/opentalk/backend/containers/typst-plugins:${typst_plugins_flavor}-${typst_plugins_version} AS typst-plugins

FROM scratch

ENV USERID=1000
ENV GROUPID=1000

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /controller/target/x86_64-unknown-linux-musl/release/opentalk-controller ./opentalk-controller

ADD example/controller.toml /etc/opentalk/controller.toml

COPY --from=typst-plugins /usr/share/typst/packages/preview/linguify/ /usr/share/typst/packages/preview/linguify/

USER $USERID:$GROUPID

EXPOSE 11311

CMD [ "./opentalk-controller" ]
