# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-inventory"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bigdecimal.workspace = true
bincode.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
derive_more = { workspace = true, features = [
  "as_ref",
  "display",
  "from",
  "from_str",
  "into",
] }
opentalk-database.workspace = true
opentalk-db-storage.workspace = true
opentalk-types-common.workspace = true
scoped-futures.workspace = true
serde = { workspace = true, features = ["derive"] }
snafu.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true
