# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-signaling-module-echo"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types-common.workspace = true
serde_json.workspace = true
