# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-signaling-core"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
opentelemetry = { workspace = true, features = ["metrics", "trace"] }
opentelemetry_sdk.workspace = true
redis = { workspace = true, features = ["connection-manager", "tokio-comp"] }

[features]
default = []
