# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
build = "build.rs"
default-run = "opentalk-controller"
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-controller"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
actix-web.workspace = true
clap = { workspace = true, features = ["derive"] }
kustos.workspace = true
log.workspace = true
opentalk-controller-core.workspace = true
opentalk-controller-service.workspace = true
opentalk-database.workspace = true
opentalk-inventory.workspace = true
opentalk-inventory-database.workspace = true
opentalk-signaling-modules.workspace = true
opentalk-types-common.workspace = true
opentalk-version.workspace = true
snafu.workspace = true

[features]
default = ["swagger"]
swagger = ["opentalk-controller-core/swagger"]

[build-dependencies]
opentalk-version.workspace = true
snafu.workspace = true
