# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-signaling-module-breakout"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
either.workspace = true
futures.workspace = true
log.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types-common.workspace = true
opentalk-types-signaling.workspace = true
opentalk-types-signaling-breakout = { workspace = true, features = ["backend"] }
parking_lot.workspace = true
redis.workspace = true
redis-args.workspace = true
serde.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
serial_test.workspace = true
