# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Authorization middleware for opentalk-controller API endpoints"
documentation = "https://docs.rs/opentalk-controller-api-authorization"
edition = "2024"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-controller-api-authorization"
publish = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
actix-web.workspace = true
