# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "Synchronization for OpenTalk Controller WebAPI endpoint authorization"
documentation = "https://docs.rs/opentalk-controller-api-authorization-synchronization"
edition = "2024"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-controller-api-authorization-synchronization"
publish = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
flume.workspace = true
log.workspace = true
mockall = { workspace = true, optional = true }
opentalk-controller-api-authorization.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[dev-dependencies]
mockall.workspace = true
opentalk-controller-api-authorization = { workspace = true, features = [
  "mockall",
] }
opentalk-types-common.workspace = true
pretty_assertions.workspace = true
tokio = { workspace = true, features = [
  "macros",
  "rt",
  "rt-multi-thread",
  "time",
] }

[features]
mockall = ["dep:mockall"]
