# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
license = "EUPL-1.2"
name = "opentalk-signaling-module-meeting-notes"
publish = false
version.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
either.workspace = true
log.workspace = true
opentalk-controller-settings.workspace = true
opentalk-etherpad-client.workspace = true
opentalk-inventory.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types-common = { workspace = true, features = ["backend"] }
opentalk-types-signaling = { workspace = true, features = ["backend"] }
opentalk-types-signaling-meeting-notes = { workspace = true, features = [
  "backend",
] }
parking_lot.workspace = true
redis.workspace = true
redis-args.workspace = true
serde.workspace = true
snafu.workspace = true
tracing.workspace = true

[dev-dependencies]
serial_test.workspace = true
tokio.workspace = true
