# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
edition = "2024"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-controller-api-actix-web"
publish = false
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
actix-web.workspace = true
opentalk-types-common.workspace = true
