# SPDX-License-Identifier: EUPL-1.2
# SPDX-FileCopyrightText: OpenTalk Team <mail@opentalk.eu>

[profile.default]
default-filter = 'all()'

[profile.ci]
default-filter = 'all()'

[test-groups]
serial = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(serial_test)'
test-group = 'serial'

[[profile.default.overrides]]
filter = 'test(/^expiring_data_hash_map::/)'
test-group = 'serial'

[profile.ci.junit]
path = "junit.xml"
