# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors.workspace = true
description = "OpenTalk Controller service facade"
documentation = "https://docs.rs/opentalk-controller-service-facade"
edition = "2024"
homepage.workspace = true
license = "EUPL-1.2"
name = "opentalk-controller-service-facade"
publish = true
repository.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
futures-core.workspace = true
openidconnect.workspace = true
opentalk-signaling-core.workspace = true
opentalk-types-api-internal.workspace = true
opentalk-types-api-v1.workspace = true
opentalk-types-common.workspace = true
strum.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
